export let questions = [
    {question:"J’ai de fortes convictions sur ce qui est vrai ou faux, bien ou mal. ",type:"theorist"},
    {question:"J’agis souvent sans considérer les conséquences possibles.",type:"activist"},
    {question:"J’ai tendance à résoudre les problèmes en utilisant une approche étape par étape.",type:"theorist"},
    {question:"Je crois que les procédures et politiques formelles restreignent les gens.",type:"activist"},
    {question:"J’ai la réputation de dire ce que je pense, simplement et directement.",type:"pragmatist"},
    {question:"Je trouve souvent que les actions basées sur des sentiments sont aussi solides que celles basées sur une réflexion et une analyse approfondies.",type:"activist"},
    {question:"J’aime le genre de travail où j’ai du temps pour une préparation et une mise en œuvre approfondies.",type:"reflector"},
    {question:"J’interroge régulièrement les gens sur leurs hypothèses de base.",type:"theorist"},
    {question:"Ce qui compte le plus, c’est de savoir si quelque chose fonctionne dans la pratique.",type:"pragmatist"},
    {question:"Je recherche activement de nouvelles expériences.",type:"activist"},
    {question:"Lorsque j’entends parler d’une nouvelle idée ou d’une nouvelle approche, je commence immédiatement à déterminer comment l’appliquer dans la pratique.",type:"pragmatist"},
    {question:"J’aime l’autodiscipline, comme surveiller mon alimentation, faire de l’exercice régulièrement, respecter une routine fixe, etc.",type:"theorist"},
    {question:"Je suis fier de faire un travail minutieux.",type:"reflector"},
    {question:"Je m’entends mieux avec les personnes logiques et analytiques et moins bien avec les personnes spontanées et « irrationnelles ».",type:"theorist"},
    {question:"Je fais attention à la façon dont j’interprète les données et j’évite de sauter aux conclusions.",type:"reflector"},
    {question:"J’aime prendre une décision avec soin après avoir pesé de nombreuses alternatives.",type:"reflector"},
    {question:"Je suis plus attiré par les idées nouvelles et inhabituelles que par les idées pratiques.",type:"activist"},
    {question:"Je n’aime pas les choses désorganisées et je préfère intégrer les choses dans un schéma cohérent.",type:"theorist"},
    {question:"J’accepte et respecte les procédures et politiques établies tant que je les considère comme un moyen efficace de faire le travail.",type:"pragmatist"},
    {question:"J’aime lier mes actions à un principe général, une norme ou une croyance.",type:"theorist"},
    {question:"Dans les discussions, j’aime aller droit au but.",type:"pragmatist"},
    {question:"J’ai tendance à avoir des relations distantes, plutôt formelles avec les gens au travail.",type:"theorist"},
    {question:"J’aime relever le défi de m’attaquer à quelque chose de nouveau et de différent.",type:"activist"},
    {question:"J’aime les gens spontanés qui aiment s’amuser.",type:"activist"},
    {question:"Je fais très attention aux détails avant de conclure.",type:"reflector"},
    {question:"J’ai du mal à produire des idées sur une impulsion.",type:"theorist"},
    {question:"Je crois qu'il faut en venir au fait immédiatement.",type:"pragmatist"},
    {question:"Je fais attention à ne pas sauter aux conclusions trop vite.",type:"reflector"},
    {question:"Je préfère avoir autant de sources d’informations que possible – plus il y a d’informations pour réfléchir, mieux c’est.",type:"reflector"},
    {question:"Les gens désinvoltes et superficiels qui ne prennent pas les choses assez au sérieux m’irritent généralement.",type:"theorist"},
    {question:"J’écoute le point de vue des autres avant de mettre mon point de vue en avant.",type:"reflector"},
    {question:"J’ai tendance à être ouvert sur ce que je ressens.",type:"activist"},
    {question:"Dans les discussions, j’aime regarder les intrigues et les intrigues des autres participants.",type:"reflector"},
    {question:"Je préfère réagir aux événements de manière spontanée et flexible plutôt que de planifier les choses à l’avance.",type:"activist"},
    {question:"J’ai tendance à être attiré par les techniques telles que les organigrammes, les plans d’urgence, etc.",type:"pragmatist"},
    {question:"Cela m’inquiète si je dois précipiter le travail pour respecter un délai serré.",type:"reflector"},
    {question:"J’ai tendance à juger les idées des gens sur leurs avantages pratiques.",type:"pragmatist"},
    {question:"Les gens calmes et attentionnés ont tendance à me mettre mal à l’aise.",type:"activist"},
    {question:"Je suis souvent irrité par les gens qui veulent précipiter les choses.",type:"reflector"},
    {question:"Il est plus important de profiter du moment présent que de penser au passé ou au futur.",type:"activist"},
    {question:"Je pense que les décisions basées sur une analyse minutieuse de toutes les informations sont meilleures que celles basées sur l’intuition.",type:"reflector"},
    {question:"J’ai tendance à être perfectionniste.",type:"theorist"},
    {question:"Dans les discussions, je produis généralement beaucoup d’idées spontanées.",type:"activist"},
    {question:"En réunion, j’avance des idées pratiques et réalistes.",type:"pragmatist"},
    {question:"Le plus souvent, les règles sont là pour être enfreintes.",type:"activist"},
    {question:"Je préfère prendre du recul par rapport à une situation et considérer toutes les perspectives.",type:"reflector"},
    {question:"Je peux souvent voir des incohérences et des faiblesses dans les arguments des autres.",type:"theorist"},
    {question:"Dans l’ensemble, je parle plus que j’écoute.",type:"activist"},
    {question:"Je vois souvent des façons meilleures et plus pratiques de faire avancer les choses.",type:"pragmatist"},
    {question:"Je pense que les rapports écrits doivent être courts et précis.",type:"pragmatist"},
    {question:"Je crois que la pensée rationnelle et logique devrait l’emporter.",type:"theorist"},
    {question:"J’ai tendance à discuter de choses spécifiques avec les gens plutôt que de m’engager dans une discussion sociale.",type:"reflector"},
    {question:"J’aime les gens qui abordent les choses de manière réaliste plutôt que théorique.",type:"pragmatist"},
    {question:"Dans les discussions, je m’impatiente avec des questions et des digressions non pertinentes.",type:"pragmatist"},
    {question:"Si j’ai un rapport à rédiger, j’ai tendance à produire beaucoup de brouillons avant de me fixer sur la version finale.",type:"reflector"},
    {question:"Je suis désireux d’essayer des choses pour voir si elles fonctionnent dans la pratique.",type:"pragmatist"},
    {question:"Je suis désireux d’atteindre des réponses via une approche logique.",type:"theorist"},
    {question:"J’aime être celui qui parle beaucoup.",type:"activist"},
    {question:"Dans les discussions, je trouve souvent que je suis réaliste, que je tiens les gens à l’essentiel et que j’évite les spéculations sauvages.",type:"pragmatist"},
    {question:"J’aime réfléchir à de nombreuses alternatives avant de me décider.",type:"reflector"},
    {question:"Dans les discussions avec les gens, je trouve souvent que je suis le plus impartial et objectif.",type:"theorist"},
    {question:"Dans les discussions, je suis plus susceptible d’adopter un « profil bas » que de prendre les devants et de parler la plupart du temps.",type:"reflector"},
    {question:"J’aime être capable de relier les actions en cours à la situation plus large à plus long terme.",type:"theorist"},
    {question:"Quand les choses tournent mal, je suis heureux de l’ignorer et de le « mettre sur le compte de l’expérience ».",type:"activist"},
    {question:"J’ai tendance à rejeter les idées sauvages et spontanées comme étant peu pratiques.",type:"pragmatist"},
    {question:"Il est préférable de bien réfléchir avant d’agir.",type:"reflector"},
    {question:"Dans l’ensemble, j’écoute plutôt que de parler.",type:"reflector"},
    {question:"J’ai tendance à être dur avec les gens qui ont du mal à adopter une approche logique.",type:"theorist"},
    {question:"La plupart du temps, je pense que la fin justifie les moyens.",type:"pragmatist"},
    {question:"Cela ne me dérange pas de blesser les gens tant que le travail est fait.",type:"pragmatist"},
    {question:"Je trouve la formalité d’avoir des objectifs et des plans spécifiques étouffante.",type:"activist"},
    {question:"Je fais généralement partie de ceux qui donnent vie à une fête.",type:"activist"},
    {question:"Je fais tout ce qui est pratique pour faire le travail.",type:"pragmatist"},
    {question:"Je m’ennuie vite du travail méthodique et minutieux.",type:"activist"},
    {question:"Je suis désireux d’explorer les hypothèses de base, les principes et les théories qui sous-tendent les choses et les événements.",type:"theorist"},
    {question:"Je suis toujours intéressé de savoir ce que les gens pensent.",type:"reflector"},
    {question:"J’aime que les réunions se déroulent de manière méthodique, en respectant l’ordre du jour établi.",type:"theorist"},
    {question:"J’évite les sujets subjectifs (partiaux) ou ambigus (peu clairs).",type:"theorist"},
    {question:"J’aime le drame et l’excitation d’une situation de crise.",type:"activist"},
    {question:"Les gens me trouvent souvent insensible à leurs sentiments.",type:"pragmatist"},
];